### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by crazy-canux** [Wildog/airline-weather.vim#3]
Looks the openweathermap api is missing.

**Comment by Wildog** [comment]
Could you say more specifically about it? I have no issues with the API currently.

**Comment by tamasd** [comment]
Their API was down for a while a couple of days ago. It made my vim unusable, because error messages were popping up all the time, so I disabled the plugin temporarly. Can you improve the error handling around weather.vim:36 (where you get the data out of the json)?

**Comment by Wildog** [comment]
I'll look into it. But I haven't encounter any API error, was it happening while getting the json or parsing the json? By the way, I believe what weather.vim:36 is doing is simply expanding the path of cache file and has nothing to do with the network.

**Comment by tamasd** [comment]
I didn't debug the issue, but the error points to the `json` map(?), and it seems that the map does not have name, weather etc keys.

**Comment by Wildog** [comment]
The status will show "API Err" when errors occurred in the latest version, and OpenWeatherMap just got my API key changed for no reason, maybe it'd be better if you apply for your own API key.
