### ISSUE TITLE
更新了地理位置天气还是不会更新

### ISSUE THREAD

**Issue by Rogerskelamen** [Wildog/airline-weather.vim#7]
最开始的时候我设置的是武汉（我本人也居住在武汉），但是比如说我设置一个北京的天气，它并不会更新至北京：
![image](https://user-images.githubusercontent.com/58795886/128619379-5adeaa42-49bc-4685-aa29-6a6be9560c3d.png)
然后我的`.weather`文件一直是wuhan：
![image](https://user-images.githubusercontent.com/58795886/128619395-a0691b0f-8abc-427e-872a-c43079cde18b.png)
当然我也Refresh过了

**Comment by Freed-Wu** [comment]
I can reproduce this bug.

**Comment by Freed-Wu** [comment]
the only one method to refresh is `rm -rf ~/.cache/.weather` :smile:

PS: and i am curious why the author name it `.weather` not `weather.json`, because `.cache` is a hidden file, it has no need to name it with prefix of `.`

**Comment by Rogerskelamen** [comment]
the method `rm -rf ~/.cache/.weather` seems feasible

but I wonder whether there is a way that I refresh the plug by `:call RefreshWeather()`

if I just add a line into weather.vim
![image](https://user-images.githubusercontent.com/58795886/129664756-587e8cb6-d907-4931-b3e2-f353fc95dba7.png)

Can this work?

**Comment by Rogerskelamen** [comment]
I think I still need to fix the source code so I can set the refresh function automatically by time

But I don't know how and where to change

**Comment by Freed-Wu** [comment]
Please try `call delete('~/.cache/.weather')`, it will be faster than `!rm -rf ~/.cache/.weather` because of it is a vim script command not shell command. :smile:

**Comment by Freed-Wu** [comment]
In detail, like it:
```diff
@@ -74,6 +74,7 @@ function! weather#get(forcerefresh) abort
 endfunction

 function! RefreshWeather()
+    call delete(expand(g:weather#cache_file))
     call weather#get(1)
     echom "Weather refreshed."
 endfunction
```

**Comment by Rogerskelamen** [comment]
> In detail, like it:
> 
> ```diff
> @@ -74,6 +74,7 @@ function! weather#get(forcerefresh) abort
>  endfunction
> 
>  function! RefreshWeather()
> +    call delete(expand(g:weather#cache_file))
>      call weather#get(1)
>      echom "Weather refreshed."
>  endfunction
> ```

Thank you for your help, this really works well and I learned a little vim script knowledge.
Actually, I still want to change the `weather#get` function so that the plugin can automatically refresh itself through the set time and the noisy problem will then be removed for good in my relief.
*I know it's going to be irrelevant about the issue, but I just want to get it done. If there is no solution, I will still close the issue*

**Comment by Freed-Wu** [comment]
Automatically refresh? I guess it is related to `autocmd`?
Can
```vim
" you can add it in your vimrc or any position you will source it
augroup refresh_weather
  autocmd!
  autocmd VimEnter * call RefreshWeather()
augroup END
```

solve your problem? I think it can refresh weather information when users start their vim. However, it will add a little vim's startup time compared to refreshing weather information manually.

**Comment by Rogerskelamen** [comment]
@Freed-Wu Maybe you are right, the `autocmd` can do the job although it costs some overhead.
Thanks for your help again, I will close the issue.
